site_name: AmbSim
site_url: https://ambsim.com/
repo_url: https://github.com/nhsengland/AmbModelOpen
repo_name: nhsengland/AmbModelOpen
nav:
  - Home: index.md
  - Problem Setting: problem.md
  - 'Representative Model': 
    - Chosen method: chosenmethod.md
    - Data Sources (Inputs): data.md 
    - Evidence and Insights (Assumptions): insights.md 
  - 'Optimized Model': 
    - Model Build Summary: run.md
    - Illustrative questions: illustrativequestions.md
    - Repository Structure: structure.md 
    - Inputs: inputs.md
    - User Settings (Config): config.md
  - 'Solution': 
    - Validation: validation.md
    - Results: results.md
  - 'User guide':
    - Starting a run: examplerun.md
    - Parameter input files: userguide.md
    - Overview of output files: interpretoutput.md
  - Glossary and reference: glossary.md
  - Contact: contact.md
theme: 
  name: material
  logo: assets/simulation_badge_M.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - search.suggest
plugins:
    - table-reader
    - search